<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Json2md</RootNamespace>
        <AssemblyName>Json2md</AssemblyName>
        <IsPackable>true</IsPackable>
        <Description>A JSON to Markdown converter, ported from json2md (JavaScript).</Description>
        <PackageId>BlueCurve.Json2md</PackageId>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>json;markdown;converter;json2md</PackageTags>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <NoWarn>$(NoWarn);CA1724;IDE0060</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitVersion.MsBuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
