<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.2.25" />
        <PackageVersion Include="IsNullEnforcer" Version="1.0.0" />
        <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="11.0.100-preview.4.26230.115" />
        <PackageVersion Include="TUnit" Version="1.48.6" />
    </ItemGroup>
</Project>
